/* Product param catalog and factory defaults. Edit per meter project. */
#ifndef DC_PARAM_CFG_H
#define DC_PARAM_CFG_H

#define PARAM_ITEM_LIST(X) \
    X(PARAM_SEASON_SWTIME, 0x4008u, DATATYPE_INT,   1u,  7u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK)) \
    X(PARAM_DAY_SWTIME,    0x4009u, DATATYPE_INT,   1u,  7u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK)) \
    X(PARAM_FEE_SWTIME,    0x400Au, DATATYPE_INT,   1u,  7u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK)) \
    X(PARAM_LADDER_SWTIME, 0x400Bu, DATATYPE_INT,   1u,  7u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK)) \
    X(PARAM_HOLIDAY_DATA,  0x4011u, DATATYPE_LINKARRAY, 20u, 12u, (FLAG_ROM | FLAG_EEPROM)) \
    X(PARAM_CALIB_DATA,    0x4012u, DATATYPE_LINKARRAY, 20u, 12u, (FLAG_ROM | FLAG_EEPROM)) \
    X(PARAM_UN,            0x4013u, DATATYPE_INT,   1u,  4u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK)) \
    X(PARAM_IB,            0x4014u, DATATYPE_INT,   1u,  4u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK)) \
    X(PARAM_IMAX,          0x4015u, DATATYPE_INT,   1u,  4u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK))

#if defined(DC_PARAM_PACK)

#include <stdint.h>

#define PARAM_ITEM_DEFAULTS(X) \
    X(PARAM_SEASON_SWTIME) \
    X(PARAM_DAY_SWTIME) \
    X(PARAM_FEE_SWTIME) \
    X(PARAM_LADDER_SWTIME) \
    X(PARAM_HOLIDAY_DATA)

static const uint8_t PARAM_SEASON_SWTIME_def[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF
};
static const uint8_t PARAM_DAY_SWTIME_def[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF
};
static const uint8_t PARAM_FEE_SWTIME_def[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF
};
static const uint8_t PARAM_LADDER_SWTIME_def[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF
};

#define PARAM_FF6 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF

static const uint8_t PARAM_HOLIDAY_DATA_def[] = {
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6
};

#undef PARAM_FF6

#endif /* DC_PARAM_PACK */

#endif
