/* Generated by dc_param_pack. Do not edit. */
#ifndef DC_PARAM_LAYOUT_H
#define DC_PARAM_LAYOUT_H

#include <stddef.h>
#include <stdint.h>
#include "dc_param.h"
#include "dc_storage_cfg.h"

typedef enum {
    PARAM_REMOTECTRL = 0u,
    PARAM_LOCALCTRL = 1u,
    PARAM_TCP_UDP_SETUP = 2u,
    PARAM_SEASON_SWTIME = 3u,
    PARAM_LINK_TEST = 4u,
    PARAM_DAY_SWTIME = 5u,
    PARAM_FEE_SWTIME = 6u,
    PARAM_LADDER_SWTIME = 7u,
    PARAM_UN = 8u,
    PARAM_IB = 9u,
    PARAM_IMAX = 10u,
    PARAM_HOLIDAY_DATA = 11u,
    PARAM_CALIB_DATA = 12u,
    PARAM_ID_SENTINEL
} E_PARAMETER_TYPE;

#define PARAM_LAYOUT_BLOCK_COUNT (9u)
#define PARAM_LAYOUT_ITEM_COUNT (13u)

#define PARAM_LAYOUT_BLOCK_0_EE_OFF (0u)
#define PARAM_LAYOUT_BLOCK_1_EE_OFF (PARAM_LAYOUT_BLOCK_0_EE_OFF + PARAM_BLOCK_SIZE)
#define PARAM_LAYOUT_BLOCK_2_EE_OFF (PARAM_LAYOUT_BLOCK_1_EE_OFF + PARAM_BLOCK_SIZE)
#define PARAM_LAYOUT_BLOCK_3_EE_OFF (PARAM_LAYOUT_BLOCK_2_EE_OFF + PARAM_BLOCK_SIZE)
#define PARAM_LAYOUT_BLOCK_4_EE_OFF (PARAM_LAYOUT_BLOCK_3_EE_OFF + PARAM_BLOCK_SIZE)
#define PARAM_LAYOUT_BLOCK_5_EE_OFF (PARAM_LAYOUT_BLOCK_4_EE_OFF + PARAM_BLOCK_SIZE)
#define PARAM_LAYOUT_BLOCK_6_EE_OFF (PARAM_LAYOUT_BLOCK_5_EE_OFF + PARAM_BLOCK_SIZE)
#define PARAM_LAYOUT_BLOCK_7_EE_OFF (PARAM_LAYOUT_BLOCK_6_EE_OFF + PARAM_BLOCK_SIZE)
#define PARAM_LAYOUT_BLOCK_8_EE_OFF (PARAM_LAYOUT_BLOCK_7_EE_OFF + PARAM_BLOCK_SIZE)
#define PARAM_EE_TOTAL (PARAM_EE_TOTAL_ALIGN(PARAM_LAYOUT_BLOCK_8_EE_OFF + PARAM_BLOCK_SIZE))
#define PARAM_EE_BAK_BASE (PARAM_EE_TOTAL)
#define PARAM_EE_BAK_SPAN (320u)
#define PARAM_EE_MAP_END (PARAM_EE_BAK_BASE + PARAM_EE_BAK_SPAN)
#define PARAM_LAYOUT_BLOCK_0_EE_BK_OFF (PARAM_EE_BAK_BASE + PARAM_LAYOUT_BLOCK_0_EE_OFF)
#define PARAM_LAYOUT_BLOCK_1_EE_BK_OFF (PARAM_EE_BAK_BASE + PARAM_LAYOUT_BLOCK_1_EE_OFF)
#define PARAM_LAYOUT_BLOCK_2_EE_BK_OFF (PARAM_EE_BAK_BASE + PARAM_LAYOUT_BLOCK_2_EE_OFF)
#define PARAM_LAYOUT_BLOCK_3_EE_BK_OFF (PARAM_EE_BAK_BASE + PARAM_LAYOUT_BLOCK_3_EE_OFF)
#define PARAM_LAYOUT_BLOCK_4_EE_BK_OFF (PARAM_EE_BAK_BASE + PARAM_LAYOUT_BLOCK_4_EE_OFF)

/* tParamBlockTable: primary slots only. bak2 = PARAM_EE_BAK_BASE + uBlockEeOff */
#define PARAM_LAYOUT_BLOCK_0_PAYLOAD (58u)
#define PARAM_LAYOUT_BLOCK_0_LEN (60u)

typedef struct {
    uint8_t PARAM_REMOTECTRL[6u];
    uint8_t PARAM_LOCALCTRL[6u];
    uint8_t PARAM_TCP_UDP_SETUP[39u];
    uint8_t PARAM_SEASON_SWTIME[7u];
    uint8_t crc[2u];
} param_layout_0_t;
typedef char param_layout_0_szchk[(sizeof(param_layout_0_t) == (size_t)PARAM_LAYOUT_BLOCK_0_LEN) ? 1 : -1];

#define PARAM_LAYOUT_BLOCK_1_PAYLOAD (60u)
#define PARAM_LAYOUT_BLOCK_1_LEN (62u)

typedef struct {
    uint8_t PARAM_LINK_TEST[60u];
    uint8_t crc[2u];
} param_layout_1_t;
typedef char param_layout_1_szchk[(sizeof(param_layout_1_t) == (size_t)PARAM_LAYOUT_BLOCK_1_LEN) ? 1 : -1];

#define PARAM_LAYOUT_BLOCK_2_PAYLOAD (60u)
#define PARAM_LAYOUT_BLOCK_2_LEN (62u)

typedef struct {
    uint8_t PARAM_LINK_TEST[60u];
    uint8_t crc[2u];
} param_layout_2_t;
typedef char param_layout_2_szchk[(sizeof(param_layout_2_t) == (size_t)PARAM_LAYOUT_BLOCK_2_LEN) ? 1 : -1];

#define PARAM_LAYOUT_BLOCK_3_PAYLOAD (30u)
#define PARAM_LAYOUT_BLOCK_3_LEN (32u)

typedef struct {
    uint8_t PARAM_LINK_TEST[30u];
    uint8_t crc[2u];
} param_layout_3_t;
typedef char param_layout_3_szchk[(sizeof(param_layout_3_t) == (size_t)PARAM_LAYOUT_BLOCK_3_LEN) ? 1 : -1];

#define PARAM_LAYOUT_BLOCK_4_PAYLOAD (21u)
#define PARAM_LAYOUT_BLOCK_4_LEN (23u)

typedef struct {
    uint8_t PARAM_DAY_SWTIME[7u];
    uint8_t PARAM_FEE_SWTIME[7u];
    uint8_t PARAM_LADDER_SWTIME[7u];
    uint8_t crc[2u];
} param_layout_4_t;
typedef char param_layout_4_szchk[(sizeof(param_layout_4_t) == (size_t)PARAM_LAYOUT_BLOCK_4_LEN) ? 1 : -1];

#define PARAM_LAYOUT_BLOCK_5_PAYLOAD (12u)
#define PARAM_LAYOUT_BLOCK_5_LEN (14u)

typedef struct {
    uint8_t PARAM_UN[4u];
    uint8_t PARAM_IB[4u];
    uint8_t PARAM_IMAX[4u];
    uint8_t crc[2u];
} param_layout_5_t;
typedef char param_layout_5_szchk[(sizeof(param_layout_5_t) == (size_t)PARAM_LAYOUT_BLOCK_5_LEN) ? 1 : -1];

#define PARAM_LAYOUT_BLOCK_6_PAYLOAD (60u)
#define PARAM_LAYOUT_BLOCK_6_LEN (62u)

typedef struct {
    uint8_t PARAM_HOLIDAY_DATA[60u];
    uint8_t crc[2u];
} param_layout_6_t;
typedef char param_layout_6_szchk[(sizeof(param_layout_6_t) == (size_t)PARAM_LAYOUT_BLOCK_6_LEN) ? 1 : -1];

#define PARAM_LAYOUT_BLOCK_7_PAYLOAD (60u)
#define PARAM_LAYOUT_BLOCK_7_LEN (62u)

typedef struct {
    uint8_t PARAM_CALIB_DATA[60u];
    uint8_t crc[2u];
} param_layout_7_t;
typedef char param_layout_7_szchk[(sizeof(param_layout_7_t) == (size_t)PARAM_LAYOUT_BLOCK_7_LEN) ? 1 : -1];

#define PARAM_LAYOUT_BLOCK_8_PAYLOAD (36u)
#define PARAM_LAYOUT_BLOCK_8_LEN (38u)

typedef struct {
    uint8_t PARAM_CALIB_DATA[36u];
    uint8_t crc[2u];
} param_layout_8_t;
typedef char param_layout_8_szchk[(sizeof(param_layout_8_t) == (size_t)PARAM_LAYOUT_BLOCK_8_LEN) ? 1 : -1];

#endif /* DC_PARAM_LAYOUT_H */

#if defined(DC_PARAM_LAYOUT_DEFINE)
#ifndef DC_PARAM_LAYOUT_TABLE_DEFINED
#define DC_PARAM_LAYOUT_TABLE_DEFINED

param_layout_0_t g_param_ram_0;
param_layout_1_t g_param_ram_1;
param_layout_2_t g_param_ram_2;
param_layout_3_t g_param_ram_3;
param_layout_5_t g_param_ram_5;
param_layout_6_t g_param_ram_6;

const uint32_t PARAM_EEPROM_ORIGIN = (uint32_t)PARAM_EEPROM_BASE;

const ST_PARAM_BLOCK_TABLE tParamBlockTable[] = {
    /* RAM_EE_BK1 */
    { PARAM_LAYOUT_BLOCK_0_EE_OFF, (uint8_t *)&g_param_ram_0, (uint16_t)sizeof(g_param_ram_0), 0x0Bu },
    { PARAM_LAYOUT_BLOCK_1_EE_OFF, (uint8_t *)&g_param_ram_1, (uint16_t)sizeof(g_param_ram_1), 0x0Bu },
    { PARAM_LAYOUT_BLOCK_2_EE_OFF, (uint8_t *)&g_param_ram_2, (uint16_t)sizeof(g_param_ram_2), 0x0Bu },
    { PARAM_LAYOUT_BLOCK_3_EE_OFF, (uint8_t *)&g_param_ram_3, (uint16_t)sizeof(g_param_ram_3), 0x0Bu },
    /* EE_BK1 */
    { PARAM_LAYOUT_BLOCK_4_EE_OFF, NULL, (uint16_t)PARAM_LAYOUT_BLOCK_4_LEN, 0x0Au },
    /* RAM_EE */
    { PARAM_LAYOUT_BLOCK_5_EE_OFF, (uint8_t *)&g_param_ram_5, (uint16_t)sizeof(g_param_ram_5), 0x03u },
    { PARAM_LAYOUT_BLOCK_6_EE_OFF, (uint8_t *)&g_param_ram_6, (uint16_t)sizeof(g_param_ram_6), 0x03u },
    /* EE */
    { PARAM_LAYOUT_BLOCK_7_EE_OFF, NULL, (uint16_t)PARAM_LAYOUT_BLOCK_7_LEN, 0x02u },
    { PARAM_LAYOUT_BLOCK_8_EE_OFF, NULL, (uint16_t)PARAM_LAYOUT_BLOCK_8_LEN, 0x02u }
    /* RAM_EE_BK2 */
    /* block 9 (bak of 0): { PARAM_LAYOUT_BLOCK_0_EE_BK_OFF, (uint8_t *)&g_param_ram_0, (uint16_t)sizeof(g_param_ram_0), 0x0Bu }, */
    /* block 10 (bak of 1): { PARAM_LAYOUT_BLOCK_1_EE_BK_OFF, (uint8_t *)&g_param_ram_1, (uint16_t)sizeof(g_param_ram_1), 0x0Bu }, */
    /* block 11 (bak of 2): { PARAM_LAYOUT_BLOCK_2_EE_BK_OFF, (uint8_t *)&g_param_ram_2, (uint16_t)sizeof(g_param_ram_2), 0x0Bu }, */
    /* block 12 (bak of 3): { PARAM_LAYOUT_BLOCK_3_EE_BK_OFF, (uint8_t *)&g_param_ram_3, (uint16_t)sizeof(g_param_ram_3), 0x0Bu }, */
    /* EE_BK2 */
    /* block 13 (bak of 4): { PARAM_LAYOUT_BLOCK_4_EE_BK_OFF, NULL, (uint16_t)PARAM_LAYOUT_BLOCK_4_LEN, 0x0Au }, */
};

const uint16_t tParamBlockTableCount = (uint16_t)PARAM_LAYOUT_BLOCK_COUNT;

const uint8_t g_param_attr_PARAM_LINK_TEST[] = { 4u, 3u, 2u, 30u };

const uint8_t g_param_attr_PARAM_CALIB_DATA[] = { 4u, 2u, 5u, 12u };

const uint8_t g_default_PARAM_SEASON_SWTIME[7u] = {
    0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0xFFu
};

const uint8_t g_default_PARAM_DAY_SWTIME[7u] = {
    0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0xFFu
};

const uint8_t g_default_PARAM_FEE_SWTIME[7u] = {
    0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0xFFu
};

const uint8_t g_default_PARAM_LADDER_SWTIME[7u] = {
    0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0xFFu
};

const ST_PARAM_TABLE tParamApiTable[] = {
    { PARAM_REMOTECTRL   , 0u, 0u , 6u  , _param_attr_PARAM_REMOTECTRL   , NULL                          },
    { PARAM_LOCALCTRL    , 0u, 6u , 6u  , _param_attr_PARAM_REMOTECTRL   , NULL                          },
    { PARAM_TCP_UDP_SETUP, 0u, 12u, 39u , _param_attr_PARAM_TCP_UDP_SETUP, NULL                          },
    { PARAM_SEASON_SWTIME, 0u, 51u, 7u  , _PARAM_ATTR_INT                , g_default_PARAM_SEASON_SWTIME },
    { PARAM_LINK_TEST    , 1u, 0u , 150u, g_param_attr_PARAM_LINK_TEST   , NULL                          },
    { PARAM_DAY_SWTIME   , 4u, 0u , 7u  , _PARAM_ATTR_INT                , g_default_PARAM_DAY_SWTIME    },
    { PARAM_FEE_SWTIME   , 4u, 7u , 7u  , _PARAM_ATTR_INT                , g_default_PARAM_FEE_SWTIME    },
    { PARAM_LADDER_SWTIME, 4u, 14u, 7u  , _PARAM_ATTR_INT                , g_default_PARAM_LADDER_SWTIME },
    { PARAM_UN           , 5u, 0u , 4u  , _PARAM_ATTR_INT                , NULL                          },
    { PARAM_IB           , 5u, 4u , 4u  , _PARAM_ATTR_INT                , NULL                          },
    { PARAM_IMAX         , 5u, 8u , 4u  , _PARAM_ATTR_INT                , NULL                          },
    { PARAM_HOLIDAY_DATA , 6u, 0u , 60u , _param_attr_PARAM_HOLIDAY_DATA , NULL                          },
    { PARAM_CALIB_DATA   , 7u, 0u , 96u , g_param_attr_PARAM_CALIB_DATA  , NULL                           }
};

const uint16_t tParamApiTableCount = (uint16_t)PARAM_LAYOUT_ITEM_COUNT;

#endif /* DC_PARAM_LAYOUT_TABLE_DEFINED */
#endif /* DC_PARAM_LAYOUT_DEFINE */
