/* Product param catalog and factory defaults. Edit per meter project. */
#ifndef DC_PARAM_CFG_H
#define DC_PARAM_CFG_H

/* Subclass IDs are assigned 0..N-1 by dc_param_pack (list order). */

#define PARAM_ITEM_LIST(X) \
    X(PARAM_SEASON_SWTIME,  DATATYPE_INT,      1u,  7u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK)) \
    X(PARAM_DAY_SWTIME,     DATATYPE_INT,      1u,  7u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK)) \
    X(PARAM_FEE_SWTIME,     DATATYPE_INT,      1u,  7u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK)) \
    X(PARAM_LADDER_SWTIME,  DATATYPE_INT,      1u,  7u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK)) \
    X(PARAM_HOLIDAY_DATA,   DATATYPE_LINKARRAY, 20u, 12u, (FLAG_ROM | FLAG_EEPROM)) \
    X(PARAM_CALIB_DATA,     DATATYPE_LINKARRAY, 20u, 12u, (FLAG_ROM | FLAG_EEPROM)) \
    X(PARAM_UN,             DATATYPE_INT,      1u,  4u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK)) \
    X(PARAM_IB,             DATATYPE_INT,      1u,  4u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK)) \
    X(PARAM_IMAX,           DATATYPE_INT,      1u,  4u, (FLAG_SRAM | FLAG_ROM | FLAG_EEPROM | FLAG_EEPROM_BAK))

#if defined(DC_PARAM_PACK)

#include <stdint.h>

#define PARAM_ITEM_DEFAULTS(X) \
    X(PARAM_SEASON_SWTIME) \
    X(PARAM_DAY_SWTIME) \
    X(PARAM_FEE_SWTIME) \
    X(PARAM_LADDER_SWTIME) \
    X(PARAM_HOLIDAY_DATA)

static const uint8_t PARAM_SEASON_SWTIME_def[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF
};
static const uint8_t PARAM_DAY_SWTIME_def[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF
};
static const uint8_t PARAM_FEE_SWTIME_def[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF
};
static const uint8_t PARAM_LADDER_SWTIME_def[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF
};

#define PARAM_FF6 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF

static const uint8_t PARAM_HOLIDAY_DATA_def[] = {
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6,
    PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6, PARAM_FF6
};

#undef PARAM_FF6

#endif /* DC_PARAM_PACK */

#endif
