/* Generated by dc_variable_pack. Do not edit. */
#ifndef DC_VARIABLE_LAYOUT_H
#define DC_VARIABLE_LAYOUT_H

#include "dc_storage_cfg.h"
#include "dc_variable_cfg.h"
#include <stddef.h>
#include <stdint.h>

typedef enum {
    VAR_DATE_TIME = 0u,
    VAR_RUN_TIME = 1u,
    VAR_WORK_TIME_BAT = 2u,
    VAR_USED_MONTH = 3u,
    VAR_ENERGY_DEC = 4u,
    VAR_INTVENY_DEC = 5u,
    VAR_RMS_VOLTAGE = 6u,
    VAR_RMS_CURRENT = 7u,
    VAR_VOLT_ANGLE = 8u,
    VAR_PHASE_ANGLE = 9u,
    VAR_ACTIVE_POWER = 10u,
    VAR_REACTIVE_POWER = 11u,
    VAR_APPARENT_POWER = 12u,
    VAR_ACTPOW_PERMIN = 13u,
    VAR_REACTPOW_PERMIN = 14u,
    VAR_POWER_FACT = 15u,
    VAR_POWER_FREQ = 16u,
    VAR_METER_TMP = 17u,
    VAR_VOLT_BATTIM = 18u,
    VAR_VOLT_BATDIS = 19u,
    VAR_STAWDS_METER = 20u,
    VAR_STAWDS_FLRPT = 21u,
    VAR_DEMAND_ACTIVE = 22u,
    VAR_DEMAND_REACTIVE = 23u,
    VAR_WORK_FEENO = 24u,
    VAR_RTC_SECMIN = 25u,
    VAR_MTWORK_EVTKEY = 26u,
} E_VARIABLE_ID;

#define VAR_LIST_A_COUNT 3u
#define VAR_LIST_B_COUNT 3u
#define VAR_LIST_C_COUNT 20u
#define VAR_LIST_D_COUNT 1u

typedef struct {
    uint8_t VAR_DATE_TIME[7u];
    uint8_t VAR_RUN_TIME[16u];
    uint8_t VAR_WORK_TIME_BAT[4u];
    uint16_t crc;
} var_layout_a_t;

typedef struct {
    uint8_t VAR_USED_MONTH[4u];
    uint8_t VAR_ENERGY_DEC[16u];
    uint8_t VAR_INTVENY_DEC[8u];
    uint16_t crc;
} var_layout_b_t;

typedef struct {
    uint8_t VAR_RMS_VOLTAGE[6u];
    uint8_t VAR_RMS_CURRENT[20u];
    uint8_t VAR_VOLT_ANGLE[6u];
    uint8_t VAR_PHASE_ANGLE[6u];
    uint8_t VAR_ACTIVE_POWER[16u];
    uint8_t VAR_REACTIVE_POWER[16u];
    uint8_t VAR_APPARENT_POWER[16u];
    uint8_t VAR_ACTPOW_PERMIN[16u];
    uint8_t VAR_REACTPOW_PERMIN[16u];
    uint8_t VAR_POWER_FACT[8u];
    uint8_t VAR_POWER_FREQ[2u];
    uint8_t VAR_METER_TMP[2u];
    uint8_t VAR_VOLT_BATTIM[2u];
    uint8_t VAR_VOLT_BATDIS[2u];
    uint8_t VAR_STAWDS_METER[14u];
    uint8_t VAR_STAWDS_FLRPT[4u];
    uint8_t VAR_DEMAND_ACTIVE[4u];
    uint8_t VAR_DEMAND_REACTIVE[4u];
    uint8_t VAR_WORK_FEENO[1u];
    uint8_t VAR_RTC_SECMIN[8u];
} var_layout_c_t;

typedef struct {
    uint8_t VAR_MTWORK_EVTKEY[8u];
} var_layout_d_t;

#define VAR_A_CRC_ADDR (uint16_t)offsetof(var_layout_a_t, crc)
#define VAR_A_END_ADDR (uint16_t)sizeof(var_layout_a_t)
#define VAR_B_CRC_ADDR (uint16_t)offsetof(var_layout_b_t, crc)
#define VAR_B_END_ADDR (uint16_t)sizeof(var_layout_b_t)
#define VAR_C_END_ADDR (uint16_t)sizeof(var_layout_c_t)
#define VAR_D_END_ADDR (uint16_t)sizeof(var_layout_d_t)

#endif /* DC_VARIABLE_LAYOUT_H */

#if defined(DC_VARIABLE_LAYOUT_DEFINE)
#ifndef DC_VARIABLE_LAYOUT_TABLE_DEFINED
#define DC_VARIABLE_LAYOUT_TABLE_DEFINED

const ST_DC_VARIABLE_TABLE tVariableApiTable[] = {
    { (uint16_t)VAR_DATE_TIME      , (uint16_t)offsetof(var_layout_a_t, VAR_DATE_TIME      ), 7u , 1u, 7u , (uint8_t)VARIABLE_TYPEA },
    { (uint16_t)VAR_RUN_TIME       , (uint16_t)offsetof(var_layout_a_t, VAR_RUN_TIME       ), 16u, 4u, 4u , (uint8_t)VARIABLE_TYPEA },
    { (uint16_t)VAR_WORK_TIME_BAT  , (uint16_t)offsetof(var_layout_a_t, VAR_WORK_TIME_BAT  ), 4u , 1u, 4u , (uint8_t)VARIABLE_TYPEA },
    { (uint16_t)VAR_USED_MONTH     , (uint16_t)offsetof(var_layout_b_t, VAR_USED_MONTH     ), 4u , 1u, 4u , (uint8_t)VARIABLE_TYPEB },
    { (uint16_t)VAR_ENERGY_DEC     , (uint16_t)offsetof(var_layout_b_t, VAR_ENERGY_DEC     ), 16u, 1u, 16u, (uint8_t)VARIABLE_TYPEB },
    { (uint16_t)VAR_INTVENY_DEC    , (uint16_t)offsetof(var_layout_b_t, VAR_INTVENY_DEC    ), 8u , 1u, 8u , (uint8_t)VARIABLE_TYPEB },
    { (uint16_t)VAR_RMS_VOLTAGE    , (uint16_t)offsetof(var_layout_c_t, VAR_RMS_VOLTAGE    ), 6u , 3u, 2u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_RMS_CURRENT    , (uint16_t)offsetof(var_layout_c_t, VAR_RMS_CURRENT    ), 20u, 5u, 4u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_VOLT_ANGLE     , (uint16_t)offsetof(var_layout_c_t, VAR_VOLT_ANGLE     ), 6u , 3u, 2u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_PHASE_ANGLE    , (uint16_t)offsetof(var_layout_c_t, VAR_PHASE_ANGLE    ), 6u , 3u, 2u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_ACTIVE_POWER   , (uint16_t)offsetof(var_layout_c_t, VAR_ACTIVE_POWER   ), 16u, 4u, 4u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_REACTIVE_POWER , (uint16_t)offsetof(var_layout_c_t, VAR_REACTIVE_POWER ), 16u, 4u, 4u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_APPARENT_POWER , (uint16_t)offsetof(var_layout_c_t, VAR_APPARENT_POWER ), 16u, 4u, 4u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_ACTPOW_PERMIN  , (uint16_t)offsetof(var_layout_c_t, VAR_ACTPOW_PERMIN  ), 16u, 4u, 4u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_REACTPOW_PERMIN, (uint16_t)offsetof(var_layout_c_t, VAR_REACTPOW_PERMIN), 16u, 4u, 4u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_POWER_FACT     , (uint16_t)offsetof(var_layout_c_t, VAR_POWER_FACT     ), 8u , 4u, 2u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_POWER_FREQ     , (uint16_t)offsetof(var_layout_c_t, VAR_POWER_FREQ     ), 2u , 1u, 2u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_METER_TMP      , (uint16_t)offsetof(var_layout_c_t, VAR_METER_TMP      ), 2u , 1u, 2u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_VOLT_BATTIM    , (uint16_t)offsetof(var_layout_c_t, VAR_VOLT_BATTIM    ), 2u , 1u, 2u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_VOLT_BATDIS    , (uint16_t)offsetof(var_layout_c_t, VAR_VOLT_BATDIS    ), 2u , 1u, 2u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_STAWDS_METER   , (uint16_t)offsetof(var_layout_c_t, VAR_STAWDS_METER   ), 14u, 7u, 2u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_STAWDS_FLRPT   , (uint16_t)offsetof(var_layout_c_t, VAR_STAWDS_FLRPT   ), 4u , 1u, 4u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_DEMAND_ACTIVE  , (uint16_t)offsetof(var_layout_c_t, VAR_DEMAND_ACTIVE  ), 4u , 1u, 4u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_DEMAND_REACTIVE, (uint16_t)offsetof(var_layout_c_t, VAR_DEMAND_REACTIVE), 4u , 1u, 4u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_WORK_FEENO     , (uint16_t)offsetof(var_layout_c_t, VAR_WORK_FEENO     ), 1u , 1u, 1u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_RTC_SECMIN     , (uint16_t)offsetof(var_layout_c_t, VAR_RTC_SECMIN     ), 8u , 2u, 4u , (uint8_t)VARIABLE_TYPEC },
    { (uint16_t)VAR_MTWORK_EVTKEY  , (uint16_t)offsetof(var_layout_d_t, VAR_MTWORK_EVTKEY  ), 8u , 1u, 8u , (uint8_t)VARIABLE_TYPED  }

};

const uint16_t tVariableApiTableCount =
    (uint16_t)(sizeof(tVariableApiTable) / sizeof(tVariableApiTable[0]));

/* Contiguous EE map: one origin, A then B then D. */
const uint16_t VAR_A_EE_BANK_SIZE = VAR_A_END_ADDR;
const uint16_t VAR_A_EE_PWR_ON_COUNT = 2u;
const uint16_t VAR_A_EE_PWR_ON_0 = 0u;
const uint16_t VAR_A_EE_PWR_ON_1 = VAR_A_END_ADDR;
const uint16_t VAR_A_EE_PWR_DWN = (uint16_t)(2u * VAR_A_END_ADDR);
const uint16_t VAR_A_EE_TOTAL = (uint16_t)(3u * VAR_A_END_ADDR);

const uint16_t VAR_B_EE_BANK_SIZE = VAR_B_END_ADDR;
const uint16_t VAR_B_EE_PWR_ON_COUNT = 2u;
const uint16_t VAR_B_EE_PWR_ON_0 = 0u;
const uint16_t VAR_B_EE_PWR_ON_1 = VAR_B_END_ADDR;
const uint16_t VAR_B_EE_PWR_DWN = (uint16_t)(2u * VAR_B_END_ADDR);
const uint16_t VAR_B_EE_TOTAL = (uint16_t)(3u * VAR_B_END_ADDR);

const uint16_t VAR_D_EE_SIZE = VAR_D_END_ADDR;

const uint32_t VAR_A_EEPROM_BASE = (uint32_t)VAR_EEPROM_BASE;
const uint32_t VAR_B_EEPROM_BASE = (uint32_t)VAR_EEPROM_BASE + (uint32_t)(3u * VAR_A_END_ADDR);
const uint32_t VAR_D_EEPROM_BASE = (uint32_t)VAR_EEPROM_BASE + (uint32_t)(3u * VAR_A_END_ADDR) + (uint32_t)(3u * VAR_B_END_ADDR);
const uint16_t VAR_EE_TOTAL = (uint16_t)((3u * VAR_A_END_ADDR) + (3u * VAR_B_END_ADDR) + VAR_D_END_ADDR);

#endif /* DC_VARIABLE_LAYOUT_TABLE_DEFINED */
#endif /* DC_VARIABLE_LAYOUT_DEFINE */
