/* Generated by dc_variable_pack. Do not edit. */
#ifndef DC_VARIABLE_LAYOUT_H
#define DC_VARIABLE_LAYOUT_H

#include <stddef.h>
#include "dc_variable_cfg.h"

typedef struct {
    uint8_t VARIABLE_DATE_TIME[7u];
    uint8_t VARIABLE_RUN_TIME[16u];
    uint8_t VARIABLE_WORK_TIME_BAT[4u];
    uint16_t crc;
} var_layout_a_t;

typedef struct {
    uint8_t VARIABLE_USED_MONTH[4u];
    uint8_t VARIABLE_ENERGY_DEC[16u];
    uint8_t VARIABLE_INTVENY_DEC[8u];
    uint16_t crc;
} var_layout_b_t;

typedef struct {
    uint8_t VARIABLE_RMS_VOLTAGE[6u];
    uint8_t VARIABLE_RMS_CURRENT[20u];
    uint8_t VARIABLE_VOLT_ANGLE[6u];
    uint8_t VARIABLE_PHASE_ANGLE[6u];
    uint8_t VARIABLE_ACTIVE_POWER[16u];
    uint8_t VARIABLE_REACTIVE_POWER[16u];
    uint8_t VARIABLE_APPARENT_POWER[16u];
    uint8_t VARIABLE_ACTPOW_PERMIN[16u];
    uint8_t VARIABLE_REACTPOW_PERMIN[16u];
    uint8_t VARIABLE_POWER_FACT[8u];
    uint8_t VARIABLE_POWER_FREQ[2u];
    uint8_t VARIABLE_METER_TMP[2u];
    uint8_t VARIABLE_VOLT_BATTIM[2u];
    uint8_t VARIABLE_VOLT_BATDIS[2u];
    uint8_t VARIABLE_STAWDS_METER[14u];
    uint8_t VARIABLE_STAWDS_FLRPT[4u];
    uint8_t VARIABLE_DEMAND_ACTIVE[4u];
    uint8_t VARIABLE_DEMAND_REACTIVE[4u];
    uint8_t VARIABLE_WORK_FEENO[1u];
    uint8_t VARIABLE_RTC_SECMIN[8u];
} var_layout_c_t;

typedef struct {
    uint8_t VARIABLE_MTWORK_EVTKEY[8u];
} var_layout_d_t;

#if defined(DC_VARIABLE_LAYOUT_DEFINE)

const STR_VARIABLE_API_TABLE tVariableApiTable[] = {
    { 0x4000u, (uint16_t)offsetof(var_layout_a_t, VARIABLE_DATE_TIME), 7u, 1u, 7u, 0u },
    { 0xE000u, (uint16_t)offsetof(var_layout_a_t, VARIABLE_RUN_TIME), 16u, 4u, 4u, 0u },
    { 0x2013u, (uint16_t)offsetof(var_layout_a_t, VARIABLE_WORK_TIME_BAT), 4u, 1u, 4u, 0u }
,
    { 0x2031u, (uint16_t)offsetof(var_layout_b_t, VARIABLE_USED_MONTH), 4u, 1u, 4u, 1u },
    { 0xE007u, (uint16_t)offsetof(var_layout_b_t, VARIABLE_ENERGY_DEC), 16u, 1u, 16u, 1u },
    { 0xE008u, (uint16_t)offsetof(var_layout_b_t, VARIABLE_INTVENY_DEC), 8u, 1u, 8u, 1u }
,
    { 0x2000u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_RMS_VOLTAGE), 6u, 3u, 2u, 2u },
    { 0x2001u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_RMS_CURRENT), 20u, 5u, 4u, 2u },
    { 0x2002u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_VOLT_ANGLE), 6u, 3u, 2u, 2u },
    { 0x2003u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_PHASE_ANGLE), 6u, 3u, 2u, 2u },
    { 0x2004u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_ACTIVE_POWER), 16u, 4u, 4u, 2u },
    { 0x2005u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_REACTIVE_POWER), 16u, 4u, 4u, 2u },
    { 0x2006u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_APPARENT_POWER), 16u, 4u, 4u, 2u },
    { 0x2007u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_ACTPOW_PERMIN), 16u, 4u, 4u, 2u },
    { 0x2008u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_REACTPOW_PERMIN), 16u, 4u, 4u, 2u },
    { 0x200Au, (uint16_t)offsetof(var_layout_c_t, VARIABLE_POWER_FACT), 8u, 4u, 2u, 2u },
    { 0x200Fu, (uint16_t)offsetof(var_layout_c_t, VARIABLE_POWER_FREQ), 2u, 1u, 2u, 2u },
    { 0x2010u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_METER_TMP), 2u, 1u, 2u, 2u },
    { 0x2011u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_VOLT_BATTIM), 2u, 1u, 2u, 2u },
    { 0x2012u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_VOLT_BATDIS), 2u, 1u, 2u, 2u },
    { 0x2014u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_STAWDS_METER), 14u, 7u, 2u, 2u },
    { 0x2015u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_STAWDS_FLRPT), 4u, 1u, 4u, 2u },
    { 0x2017u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_DEMAND_ACTIVE), 4u, 1u, 4u, 2u },
    { 0x2018u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_DEMAND_REACTIVE), 4u, 1u, 4u, 2u },
    { 0xE003u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_WORK_FEENO), 1u, 1u, 1u, 2u },
    { 0xE205u, (uint16_t)offsetof(var_layout_c_t, VARIABLE_RTC_SECMIN), 8u, 2u, 4u, 2u }
,
    { 0xE100u, (uint16_t)offsetof(var_layout_d_t, VARIABLE_MTWORK_EVTKEY), 8u, 1u, 8u, 3u }
};

const uint16_t tVariableApiTableCount =
    (uint16_t)(sizeof(tVariableApiTable) / sizeof(tVariableApiTable[0]));

const uint16_t VAR_A_CRC_ADDR = (uint16_t)offsetof(var_layout_a_t, crc);
const uint16_t VAR_A_END_ADDR = (uint16_t)sizeof(var_layout_a_t);
const uint16_t VAR_B_CRC_ADDR = (uint16_t)offsetof(var_layout_b_t, crc);
const uint16_t VAR_B_END_ADDR = (uint16_t)sizeof(var_layout_b_t);
const uint16_t VAR_C_END_ADDR = (uint16_t)sizeof(var_layout_c_t);
const uint16_t VAR_D_END_ADDR = (uint16_t)sizeof(var_layout_d_t);

/* Contiguous EE map: one origin, A then B then D. */
const uint16_t VAR_A_EE_BANK_SIZE = VAR_A_END_ADDR;
const uint16_t VAR_A_EE_PWR_ON_COUNT = 2u;
const uint16_t VAR_A_EE_PWR_ON_0 = 0u;
const uint16_t VAR_A_EE_PWR_ON_1 = VAR_A_END_ADDR;
const uint16_t VAR_A_EE_PWR_DWN = (uint16_t)(2u * VAR_A_END_ADDR);
const uint16_t VAR_A_EE_TOTAL = (uint16_t)(3u * VAR_A_END_ADDR);

const uint16_t VAR_B_EE_BANK_SIZE = VAR_B_END_ADDR;
const uint16_t VAR_B_EE_PWR_ON_COUNT = 2u;
const uint16_t VAR_B_EE_PWR_ON_0 = 0u;
const uint16_t VAR_B_EE_PWR_ON_1 = VAR_B_END_ADDR;
const uint16_t VAR_B_EE_PWR_DWN = (uint16_t)(2u * VAR_B_END_ADDR);
const uint16_t VAR_B_EE_TOTAL = (uint16_t)(3u * VAR_B_END_ADDR);

const uint16_t VAR_D_EE_SIZE = VAR_D_END_ADDR;

const uint32_t VAR_A_EEPROM_BASE = (uint32_t)VAR_EEPROM_BASE;
const uint32_t VAR_B_EEPROM_BASE = (uint32_t)VAR_EEPROM_BASE + (uint32_t)VAR_A_EE_TOTAL;
const uint32_t VAR_D_EEPROM_BASE = (uint32_t)VAR_EEPROM_BASE + (uint32_t)VAR_A_EE_TOTAL + (uint32_t)VAR_B_EE_TOTAL;
const uint16_t VAR_EE_TOTAL = (uint16_t)(VAR_A_EE_TOTAL + VAR_B_EE_TOTAL + VAR_D_EE_SIZE);

#endif /* DC_VARIABLE_LAYOUT_DEFINE */

#endif
